---
- name: config elk server with docker
  hosts: elk
  become: true
  tasks:
  - name: Install docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: install python3-pip
    apt:
      name: python3-pip
      state: present

  - name: install docker module with pip
    pip:
      name: docker
      state: present

  - name: download and launch docker elk container
    docker_container:
      name: sebp
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044

  - name: enable docker service
    systemd:

  - name: use more memory
    sysctl:
      name: vm.max_map_count
      value: "262144"
      state: present
      reload: yes
