---
- name: installing and launch filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
    
  - name: install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat start
    command: service filebeat start

  - name: enable on boot
    systemd:
      name: filebeat
      enabled: yes

  - name: download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat config
    copy:
     src: /etc/ansible/files/metricbeat
     dest: /etc/metricbeat/metricbeat.yml

  - name: run metric beat enable command
    command: metricbeat modules enable docker

  - name: setup metric beat
    command: metricbeat setup

  - name: start metricbeat
    command: service metricbeat start

  - name: enable metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
